name: Deploy Discord Bot

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
- name: Deploy
  run: |
    python -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
    python bot.py